apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: employee-ci
spec:
  params:
    - name: GIT_URL
    - name: GIT_REVISION
      default: main
    - name: IMAGE
    - name: VERSION

  workspaces:
    - name: shared-workspace

  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: revision
          value: $(params.GIT_REVISION)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: maven
      runAfter: ["clone"]
      taskRef:
        name: maven-build
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: docker
      runAfter: ["maven"]
      taskRef:
        name: docker-build-push
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: VERSION
          value: $(params.VERSION)
      workspaces:
        - name: source
          workspace: shared-workspace
